### ISSUE TITLE
Are there any examples to show how to use this library?

### ISSUE THREAD

**Issue by yc-huang** [nthparty/oblivious#3]

**Comment by lapets** [comment]
The [otc](https://github.com/nthparty/otc) library implements a simple oblivious transfer (OT) protocol and relies on oblivious; there is a short tutorial/overview of otc here: [https://medium.com/nthparty/privacy-preserving-information-exchange-using-python-1a4a11bed3d5](https://medium.com/nthparty/privacy-preserving-information-exchange-using-python-1a4a11bed3d5). The [oprf](https://github.com/nthparty/oprf) library also uses oblivious, and one example of a real-world application of OPRFs (using a similar [JavaScript OPRF library](https://github.com/multiparty/oprf)) is this paper: [https://dl.acm.org/doi/10.1145/3209811.3212699](https://dl.acm.org/doi/10.1145/3209811.3212699).

More generally, this library's target audience is developers (1) who are already familiar with the underlying mathematics and (2) who want to quickly implement _for full-stack and/or cloud-based environments_ published MPC protocols (or their own protocol variants) that rely on elliptic curve primitives. It is not intended as a general-purpose library for implementing secure computation workflows, though with some work that is certainly possible to do.

We hope this helps!
