### ISSUE TITLE
How to use this library to implement oblivious transfer?

### ISSUE THREAD

**Issue by yxtj** [nthparty/oblivious#6]
Hi. I am looking for a library to implement the oblivious transfer.
The readme file says this library can be used to do so. But I do not know how to do it.
Is that possible to add some example code in the readme file or add an example folder with scripts implementing the OPRF, OT, and PSI?

**Comment by lapets** [comment]
This library is leveraged within a few other libraries for OT, OPRF, and PSI, which can be referenced as examples illustrating its use:

* the [otc](https://github.com/nthparty/otc) library uses this library to implement a [simple oblivious transfer protocol](https://eprint.iacr.org/2015/267) (with a detailed description of the implementation available at https://medium.com/nthparty/privacy-preserving-information-exchange-using-python-1a4a11bed3d5);
* the [oprf](https://github.com/nthparty/oprf) library uses this library to implement a simple OPRF;
* the [nthcommunity](https://github.com/nthparty/nthcommunity) open-source client component uses this library to implement the client-side portion of an extended PSI protocol.

We hope the above examples help and are sufficient. Given the broad applicability of this library, we will avoid adding specific examples to this repository.
